name: PYPI Publish

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build-and-publish:
    if: github.repository == 'picomet/picomet'
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pro
      url: https://pypi.org/p/picomet
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: python -m pip install setuptools wheel twine

      - name: Build distributions
        run: python setup.py sdist bdist_wheel

      - name: Test distributions
        run: twine check dist/*

      - name: Publish package to PyPI
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
